[package]
name = "seymour"
version = "0.1.0"
authors = ["Jay Vana <jaysvana@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
dotenv = "*"
env_logger = "*"
futures = "*"
itertools = "*"
log = "*"
sqlx = { version = "*", default-features = false, features = ["runtime-tokio-native-tls", "macros", "migrate", "offline", "sqlite"] }
thiserror = "*"
tokio = "0.2"
tokio-native-tls = "*"
native-tls = "*"
url = "*"
