CREATE TABLE IF NOT EXISTS feed_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feed_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL,
  url TEXT NOT NULL,

  FOREIGN KEY(feed_id) REFERENCES feeds(id)
);
